# Generated by Django 4.2.26 on 2025-12-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_shift_order_field_in_InAbsence_table'),
        ('cms', '0006_add_shift_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='user_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='app.users'),
        ),
    ]
