# Generated by Django 4.2.26 on 2025-12-26 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_shift_order_field_in_InAbsence_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='boss_di',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users'),
        ),
    ]
