# Generated by Django 4.2.26 on 2026-01-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_inabsences_is_from_leave_inabsences_leave_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overtime_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to='app.users')),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='app.users')),
            ],
        ),
    ]
