# Generated by Django 4.2.26 on 2026-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_overtimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimes',
            old_name='end_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='overtimes',
            name='start_time',
        ),
        migrations.AddField(
            model_name='overtimes',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimes',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimes',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimes',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
