# Generated by Django 4.2.26 on 2026-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_end_time_overtimes_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimes',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('DIVISI APPROVED', 'Divisi Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
