# Generated by Django 4.2.26 on 2026-08-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_telegramlinktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('PKWT', 'Perjanjian Kerja Waktu Tertentu'), ('PKWTT', 'Perjanjian Kerja Waktu Tidak Tertentu'), ('MAGANG', 'Magang'), ('OUTSOURCE', 'Ahli Daya')], default='PKWT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('PERMANENT', 'Permanent')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HRD', 'HRD')], max_length=20)),
                ('days_remaining', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.employeecontract')),
            ],
        ),
    ]
