# Generated by Django 4.2.26 on 2026-08-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_employeecontract_contractnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractnotification',
            old_name='days_remaining',
            new_name='reminder_day',
        ),
    ]
