# Generated by Django 4.2.26 on 2026-02-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='user',
            new_name='nik',
        ),
        migrations.RenameField(
            model_name='usersalarycomponent',
            old_name='user',
            new_name='nik',
        ),
    ]
